### PR TITLE
Integrate codecov

### PR DESCRIPTION
**Pull request by ShreyamsJain**
Installed codecov as per https://github.com/codecov/example-ruby

Environment variables have been set as per
https://documentation.codeship.com/continuous-integration/set-environment-variables/

### CODE REVIEW

**Comment by lasley** [comment]
@ShreyamsJain - this branch is in conflict now that we got Devise merged

**Comment by erinmorrissey** [comment]
Don't think I resolved this merge conflict correctly, since it's saying there are now 20 commits to be merged and 25 files changed...unless this makes sense since 3-4 merges to master were made since this PR was opened?

**Comment by ShreyamsJain** [comment]
I performed a git pull from my branch
resolved the conflicts, then tried to merge, i was getting the message "you are 20 commits ahead of master". so i did a git reset --hard on master thinking i have done something wrong on my local master. I am not sure why it is showing 20 commits on master, which the conflicts i resolved were only on 3 files

**Comment by lasley** [comment]
Not fully sure what happened here, but I think you merged the wrong way. I performed some wizardry to bring you back to before this happened. Try again!
- http://stackoverflow.com/questions/16955980/git-merge-master-into-feature-branch
- https://githowto.com/resolving_conflicts
- https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

**Comment by erinmorrissey** [comment]
@ShreyamsJain Looks like I mucked it up so you go ahead with the update push.

**Comment by wdehaes** [comment]
@ShreyamsJain since we are using rspec, shouldn't we put the codecov code in rspec foldr rather than test? I tried googling it but I couldn't find an example of codecov and rspec used together, so I might be totally wrong.

**Comment by lasley** [comment]
Yup https://github.com/coderanger/rspec-command/blob/master/spec/spec_helper.rb#L27

**Comment by ShreyamsJain** [comment]
Thanks Will @wdehaes for pointing that out. I will fix that

**Comment by ShreyamsJain** [comment]
Team, please review. I have just moved the code from test/helper.rb to spec/spec_helper.rb

**Comment by lasley** [comment]
👍  although you probably want to filter out any gems, specs, and tests in order to get an accurate number

**Comment by erinmorrissey** [comment]
I think the /test/test_helper.rb file can be removed from this push? I thought we didn't need anything in a /test directory since we're using Rspec and not Rails' default test functionality...

**Comment by lasley** [comment]
Yeah it can be destroyed along with everything in the tests folder

**Comment by erinmorrissey** [comment]
Then a second 👍  from me with the removal of /test/test_helper.rb.

**Comment by ShreyamsJain** [comment]
Thanks for the review. I will go ahead and remove test folder and then push it.

**Comment by lasley** [comment]
@ShreyamsJain Rebased your changes onto master. If this passes, go ahead with the plan of removing test folder and merging yourself.

If no pass, please make necessary changes for a 💚

**Comment by lasley** [comment]
Thought so 🔴

**Comment by lasley** [comment]
FYI @ShreyamsJain this is in conflict

**Comment by lasley** [comment]
@ShreyamsJain - there are still build errors. We cannot merge until green.

**Comment by lasley** [comment]
@ShreyamsJain - I would like to see this merged. These build errors should be simple to fix, can you please take care of it ASAP?

**Comment by ShreyamsJain** [comment]
Sure @lasley

**Comment by ShreyamsJain** [comment]
@lasley The build errors are fixed. Shall I go ahead and merge it?

**Review by lasley — APPROVED** [review]

**Comment by lasley** [comment]
Thanks @ShreyamsJain

**Pull request merged**
